# Generated by Django 4.2.11 on 2024-04-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alter_avatar_imagen_alter_entregable_entregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
